[package]
name = "smaa"
version = "0.1.0"
authors = ["Jonathan Behrens <fintelia@gmail.com>"]
description = "A library for post process antialiasing using SMAA"
repository = "https://github.com/fintelia/gfx_smaa"
keywords = ["graphics", "antialiasing", "SMAA"]
categories = ["rendering", "game-engines"]
license = "MIT"
edition = "2018"

[dependencies]
anyhow = "1.0.38"
naga = { version = "0.3.1", features = ["glsl-in"] }
wgpu = "0.7.0"

[dev-dependencies]
winit = "0.24.0"
futures = "0.3.12"
